"LR": 2.5e-4
"NUM_ENVS": 1
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 2e5
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "MPE_simple_facmac_v1"
"ENV_KWARGS": 
  "score_function": "min"
  "num_adversaries": 2
"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 10

# WandB Params
"ENTITY": "jaxmarl"
"NAME": "ippo_ff_mpe_facmac"
"PROJECT": "neurips2024"
"WANDB_MODE" : "online"

# Checkpointing
"SAVE_PATH": "ckpt"