"LR": 5e-4
"NUM_ENVS": 1024
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 1e10
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENV_NAME": "hanabi"
"ENV_KWARGS": {}
"ANNEAL_LR": False

# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": ""
"PROJECT": ""