"LR": 2.5e-4
"NUM_ENVS": 64
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 1e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"SEED": 30
"ENV_NAME": "investment"
"ENV_KWARGS": {}
"ANNEAL_LR": True
"DISABLE_JIT": True
"DEVICE": 0
"ENTITY": ""
"PROJECT": "jaxmarl-investment"
"WANDB_MODE": "disabled"