"TOTAL_TIMESTEPS": 5e6
"NUM_ENVS": 64
"NUM_STEPS": 16
"HIDDEN_SIZE": 512
"NUM_LAYERS": 2
"NORM_TYPE": "layer_norm"
"NORM_INPUT": False
"EPS_START": 1.0
"EPS_FINISH": 0.2
"EPS_DECAY": 0.2
"MAX_GRAD_NORM": 10
"NUM_MINIBATCHES": 16
"NUM_EPOCHS": 4
"LR": 0.000075
"LR_LINEAR_DECAY": True
"LAMBDA": 0.5
"GAMMA": 0.99

# env
"ENV_NAME": "overcooked"
"ENV_KWARGS": 
  "layout" : "counter_circuit"
"REW_SHAPING_HORIZON": 2.5e6

# evaluate
"TEST_DURING_TRAINING": True
"TEST_INTERVAL": 0.01 # as a fraction of updates, i.e. log every 5% of training process
"TEST_NUM_STEPS": 400
"TEST_NUM_ENVS": 512 # number of episodes to average over, can affect performance

#"ALG_NAME": "pqn_vdn_cnn" # if you want to change the name of the algo in the metrics

