"NUM_ENVS": 32
"NUM_STEPS": 256
"BUFFER_SIZE": 1024
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 10e7
"AGENT_HIDDEN_DIM": 64
"AGENT_INIT_SCALE": 2.
"PARAMETERS_SHARING": True
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.1
"EPSILON_ANNEAL_TIME": 1e6
"MIXER_EMBEDDING_DIM": 32
"MIXER_HYPERNET_HIDDEN_DIM": 64
"MIXER_INIT_SCALE": 0.0001
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 200
"LR": 0.0001
"LR_LINEAR_DECAY": False
"EPS_ADAM": 0.00001
"WEIGHT_DECAY_ADAM": 0.00001
"TD_LAMBDA_LOSS": False
"TD_LAMBDA": 0.6
"GAMMA": 0.99
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000