"NUM_ENVS": 8
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2050000
"AGENT_HIDDEN_DIM": 64
"AGENT_INIT_SCALE": 2.
"PARAMETERS_SHARING": True
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MIXER_EMBEDDING_DIM": 32
"MIXER_HYPERNET_HIDDEN_DIM": 64
"MIXER_INIT_SCALE": 0.00001
"MAX_GRAD_NORM": 25
"TARGET_UPDATE_INTERVAL": 200
"LR": 0.005
"LR_LINEAR_DECAY": True
"EPS_ADAM": 0.001
"WEIGHT_DECAY_ADAM": 0.00001
"TD_LAMBDA_LOSS": True
"TD_LAMBDA": 0.6
"GAMMA": 0.9
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000
"SAMPLE_SIZE": 5
"MANUAL_ALPHA_ESTIMATES": null
"LR_ALPHA": 0.001
"ALG_NAME": shaq