"NUM_ENVS": 8
"N_MINI_UPDATES": 1
"NUM_STEPS": 25
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2050000
"AGENT_INIT_SCALE": 1.
"AGENT_HIDDEN_DIM": 32
"AGENT_TRANSF_NUM_LAYERS": 2
"AGENT_TRANSF_NUM_HEADS": 8
"AGENT_TRANSF_DIM_FF": 128
"MIXER_INIT_SCALE": 0.01
"MIXER_TRANSF_NUM_LAYERS": 2
"MIXER_TRANSF_NUM_HEADS": 8
"MIXER_TRANSF_DIM_FF": 128
"USE_FAST_ATTENTION": True 
"SCALE_INPUTS": True 
"EMBEDDER_USE_RELU": False
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MAX_GRAD_NORM": 10.
"TARGET_UPDATE_INTERVAL": 200 
"LR": 0.001
"LR_DECAY_TYPE": 
"EPS_ADAM": 0.000001
"TD_LAMBDA_LOSS": True
"TD_LAMBDA": 0.6
"GAMMA": 0.9
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000